baseurl = "https://www.naestradadevops.com"
title = "Na Estrada DevOps"
languageCode = "pt-br"
paginate = "10" # Number of posts per page
theme = "beautifulhugo"
pygmentsUseClasses = true
pygmentCodeFences = true
disqusShortname = "naestradadevops"
googleAnalytics = "UA-88288312-2"

[Params]
  subtitle = "Uma conversa quase formal sobre DevOps"
  logo = "/img/M-15_centerline_1917_logo.jpg"
  favicon = "/M-15_centerline_1917_icon.ico"
  dateFormat = "2 January, 2006"
  commit = false
  rss = true
  comments = true

[Author]
  name = "Fernando Ike"
  email = "naestradadevops@gmail.com"


[[menu.main]]
    name = "Sobre"
    url = "/page/sobre/"
    weight = 3

[[menu.main]]
    name = "Perguntório"
    url = "/page/perguntorio/"
    weight = 3
